// Archivo corregido para Nuxt routeRules.
// Contiene SOLO redirects 301 con equivalente real.
// Las URLs legacy sin equivalente se responden como 410 desde server/middleware/legacy-notfound-redirect.ts.

export const redirectRouteRules = {
  "/ca/categoria-producte/punt-de-venda": { redirect: { to: "/categorias/expositores", statusCode: 301 } },
  "/ca/estrenem-una-taula-de-tall-digital-amb-infinites-possibilitats": { redirect: { to: "/productos/flyers-con-forma-personalizados", statusCode: 301 } },
  "/ca/manual-para-hacer-un-buen-flyer": { redirect: { to: "/como-preparar-archivos", statusCode: 301 } },
  "/ca/p/ca/producte/samarretes": { redirect: { to: "/productos/dorsales-carrera", statusCode: 301 } },
  "/ca/producte/acreditacions": { redirect: { to: "/productos/acreditaciones-personalizadas", statusCode: 301 } },
  "/ca/producte/cataleg-i-revistes-amb-grapa": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/ca/producte/doming-gota-de-resina": { redirect: { to: "/productos/etiquetas-doming", statusCode: 301 } },
  "/ca/producte/estovalles-individuals": { redirect: { to: "/productos/manteles-individuales-personalizados", statusCode: 301 } },
  "/ca/producte/laminat-velleda": { redirect: { to: "/productos/vinilo-suelo-personalizado", statusCode: 301 } },
  "/ca/producte/penjador-dampolles": { redirect: { to: "/productos/colgador-de-botellas-personalizado", statusCode: 301 } },
  "/ca/producte/plans-arquitecte": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/ca/producte/roll-up": { redirect: { to: "/productos/roll-up-personalizado", statusCode: 301 } },
  "/ca/producte/samarretes": { redirect: { to: "/productos/dorsales-carrera", statusCode: 301 } },
  "/categoria-producto/punto-de-venta": { redirect: { to: "/categorias/expositores", statusCode: 301 } },
  "/category": { redirect: { to: "/categorias", statusCode: 301 } },
  "/category/articulos-para-eventos": { redirect: { to: "/categorias/eventos", statusCode: 301 } },
  "/category/calendario-de-mesa": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/category/calendario-de-mesa/2": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/category/carteleria": { redirect: { to: "/categorias/gran-formato", statusCode: 301 } },
  "/category/folletos": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/category/hosteleria-restauracion": { redirect: { to: "/categorias/hosteleria-restauracion", statusCode: 301 } },
  "/category/impresion-de-libros": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/category/impresion-digital-gran-formato": { redirect: { to: "/categorias/gran-formato", statusCode: 301 } },
  "/category/imprimir-etiquetas-adhesivas-personalizadas": { redirect: { to: "/categorias/adhesivos-personalizados", statusCode: 301 } },
  "/category/imprimir-folletos": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/category/material-publicitario": { redirect: { to: "/categorias/publicidad-oficina/material-publicitario", statusCode: 301 } },
  "/category/papeleria-para-oficina": { redirect: { to: "/categorias/publicidad-oficina/material-oficina", statusCode: 301 } },
  "/category/publicidad-oficina": { redirect: { to: "/categorias/publicidad-oficina", statusCode: 301 } },
  "/category/sant-jordi-2025": { redirect: { to: "/productos/fundas-sant-jordi", statusCode: 301 } },
  "/category/soportes-rigidos": { redirect: { to: "/categorias/gran-formato/material-rigido", statusCode: 301 } },
  "/category/tarjetones-personalizables": { redirect: { to: "/productos/invitaciones-y-tarjetones-personalizados", statusCode: 301 } },
  "/category/tips-y-consejos/feed": { redirect: { to: "/como-preparar-archivos", statusCode: 301 } },
  "/color-pantone": { redirect: { to: "/como-preparar-archivos", statusCode: 301 } },
  "/estrenamos-una-mesa-de-corte-digital-esko": { redirect: { to: "/productos/flyers-con-forma-personalizados", statusCode: 301 } },
  "/expositores-publicitarios": { redirect: { to: "/categorias/expositores", statusCode: 301 } },
  "/impresion-digital-gran-formato": { redirect: { to: "/categorias/gran-formato", statusCode: 301 } },
  "/page/calendarios-2026-mesa-espiral": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/page/calendarios-2026-ms": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/page/calendarios-2026-pared-espiral": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/page/calendarios-2026-pared-grapado": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/page/calendarios2026": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/page/sant-jordi-2025": { redirect: { to: "/productos/fundas-sant-jordi", statusCode: 301 } },
  "/pared-revista": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/acreditaciones-presupuesto": { redirect: { to: "/productos/acreditaciones-personalizadas", statusCode: 301 } },
  "/product/acreditaciones-presupuesto/printestimate": { redirect: { to: "/productos/acreditaciones-personalizadas", statusCode: 301 } },
  "/product/agendas-personalizadas-presupuesto/printestimate": { redirect: { to: "/productos/agendas-personalizadas", statusCode: 301 } },
  "/product/aluminio-dibond-presupuesto/printestimate": { redirect: { to: "/productos/panel-dibond-personalizado", statusCode: 301 } },
  "/product/bloc-notas-presupuesto/printestimate": { redirect: { to: "/productos/blocs-notas", statusCode: 301 } },
  "/product/bobina-de-etiquetas-adhesivas-presupuesto/printestimate": { redirect: { to: "/productos/etiquetas-adhesivas-en-bobina", statusCode: 301 } },
  "/product/calendario-de-mesa": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-de-mesa-7-21x10/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-de-mesa-presupuesto/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-de-mesa/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-iman-presupuesto/printestimate": { redirect: { to: "/productos/imanes-publicitarios", statusCode: 301 } },
  "/product/calendario-mesa-eco": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-pared": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-pared-espiral/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-pared-presupuesto/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-pared-wire-o": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-pared-wire-o-presupuesto/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-pared-wire-o/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-pared/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-poster-presupuesto/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-revista-pared-eco/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-sobremesa-presupuesto/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendario-triangular-eco/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendarios-sobremesa-wire-o": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/calendarios-sobremesa-wire-o/printestimate": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/product/carpeta-de-anillas-presupuestos": { redirect: { to: "/productos/archivadores-personalizados", statusCode: 301 } },
  "/product/cartas-restaurante-presonalizadas-presupuesto/printestimate": { redirect: { to: "/productos/cartas-restaurante-personalizadas", statusCode: 301 } },
  "/product/cartel-a3-presupuesto/printestimate": { redirect: { to: "/productos/posters-personalizados", statusCode: 301 } },
  "/product/cartel-backlight-presupuesto/printestimate": { redirect: { to: "/productos/cajas-de-luz-personalizadas", statusCode: 301 } },
  "/product/catalogo-encolado-tapa-dura-presupuesto": { redirect: { to: "/productos/encuadernacion-cosida-tapa-dura", statusCode: 301 } },
  "/product/colgador-botellas-presupuesto/printestimate": { redirect: { to: "/productos/colgador-de-botellas-personalizado", statusCode: 301 } },
  "/product/cuadriptico-presupuesto/printestimate": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/product/cupones-promocionales-presupuesto/printestimate": { redirect: { to: "/productos/cupones-promocionales", statusCode: 301 } },
  "/product/diplomas-para-imprimir-presupuesto": { redirect: { to: "/productos/diplomas-personalizados", statusCode: 301 } },
  "/product/diplomas-para-imprimir-presupuesto/printestimate": { redirect: { to: "/productos/diplomas-personalizados", statusCode: 301 } },
  "/product/diptico": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/product/diptico-presupuesto/printestimate": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/product/diptico/printestimate": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/product/dipticos-llave-habitacion-presupuesto/printestimate": { redirect: { to: "/productos/tarjeta-habitacion-hotel", statusCode: 301 } },
  "/product/doming-gota-resina-presupuesto/printestimate": { redirect: { to: "/productos/etiquetas-doming", statusCode: 301 } },
  "/product/encuadernado-espiral-presupuesto/printestimate": { redirect: { to: "/productos/encuadernacion-wire-o", statusCode: 301 } },
  "/product/etiquetas-adhesivas-presupuesto/printestimate": { redirect: { to: "/categorias/adhesivos-personalizados", statusCode: 301 } },
  "/product/etiquetas-en-vinilo-adhesivo-presupuesto/printestimate": { redirect: { to: "/categorias/adhesivos-personalizados", statusCode: 301 } },
  "/product/expositor-de-mesa-peana-presupuesto/printestimate": { redirect: { to: "/categorias/expositores", statusCode: 301 } },
  "/product/expositor-de-suelo": { redirect: { to: "/productos/expositores-suelo-personalizados", statusCode: 301 } },
  "/product/expositor-de-suelo-con-peana-presupuesto/printestimate": { redirect: { to: "/categorias/expositores", statusCode: 301 } },
  "/product/expositores-de-mostrador-presupuesto/printestimate": { redirect: { to: "/categorias/expositores", statusCode: 301 } },
  "/product/flyers": { redirect: { to: "/productos/flyers-personalizados", statusCode: 301 } },
  "/product/flyers-presupuesto/printestimate": { redirect: { to: "/productos/flyers-personalizados", statusCode: 301 } },
  "/product/flyers/printestimate": { redirect: { to: "/productos/flyers-personalizados", statusCode: 301 } },
  "/product/folletos-troquelados-presupuesto/printestimate": { redirect: { to: "/productos/flyers-con-forma-personalizados", statusCode: 301 } },
  "/product/identificador-maleta-presupuesto/printestimate": { redirect: { to: "/productos/identificador-maleta", statusCode: 301 } },
  "/product/impresion-carton-pluma-presupuesto": { redirect: { to: "/productos/panel-foam-personalizado", statusCode: 301 } },
  "/product/impresion-en-lona-presupuesto/printestimate": { redirect: { to: "/productos/lona-publicitaria", statusCode: 301 } },
  "/product/impresion-en-metacrilato-presupuesto/printestimate": { redirect: { to: "/productos/metacrilato-personalizado", statusCode: 301 } },
  "/product/impresion-en-pvc-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-pvc-personalizadas", statusCode: 301 } },
  "/product/imprimir-fotos-en-lienzos-presupuesto": { redirect: { to: "/productos/carteles-personalizados-gran-formato", statusCode: 301 } },
  "/product/imprimir-fotos-en-lienzos-presupuesto/printestimate": { redirect: { to: "/productos/carteles-personalizados-gran-formato", statusCode: 301 } },
  "/product/imprimir-photocall-presupuesto/printestimate": { redirect: { to: "/productos/photocall-personalizado", statusCode: 301 } },
  "/product/imprimir-tarjeta-de-citas": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/imprimir-tarjeta-de-citas-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/imprimir-tarjeta-de-citas/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/imprimir-vinilo-adhesivo-presupuesto/printestimate": { redirect: { to: "/categorias/adhesivos-personalizados", statusCode: 301 } },
  "/product/lanyards-personalizados-presupuesto": { redirect: { to: "/productos/lanyards-eventos-barcelona", statusCode: 301 } },
  "/product/lanyards-personalizados-presupuesto/printestimate": { redirect: { to: "/productos/lanyards-eventos-barcelona", statusCode: 301 } },
  "/product/libretas-personalizadas-presupuesto/printestimate": { redirect: { to: "/productos/libretas-personalizadas", statusCode: 301 } },
  "/product/libro-tapa-dura-presupuesto/printestimate": { redirect: { to: "/productos/encuadernacion-cosida-tapa-dura", statusCode: 301 } },
  "/product/libro-tesis-presupuesto/printestimate": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/product/libros-de-tapa-blanda-presupuesto/printestimate": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/product/mantel-hule-presupuesto/printestimate": { redirect: { to: "/productos/hule-personalizado", statusCode: 301 } },
  "/product/manteles-individuales-presupuesto/printestimate": { redirect: { to: "/productos/manteles-individuales-personalizados", statusCode: 301 } },
  "/product/marcos-click-system": { redirect: { to: "/productos/marcos-click-system-personalizados", statusCode: 301 } },
  "/product/minutas-impresas-presupuesto/printestimate": { redirect: { to: "/productos/minutas-boda", statusCode: 301 } },
  "/product/nombres-sobremesa-presupuesto": { redirect: { to: "/productos/nombres-sobremesa-personalizados", statusCode: 301 } },
  "/product/papel-autocopiativo-presupuesto/printestimate": { redirect: { to: "/productos/talonarios-autocopiativos-personalizados", statusCode: 301 } },
  "/product/photocall-magnetico-presupuesto/printestimate": { redirect: { to: "/productos/photocall-personalizado", statusCode: 301 } },
  "/product/photocall-tela-presupuesto/printestimate": { redirect: { to: "/productos/photocall-personalizado", statusCode: 301 } },
  "/product/pizara-velleda-presupuesto/printestimate": { redirect: { to: "/productos/vinilo-suelo-personalizado", statusCode: 301 } },
  "/product/planos-de-arquitectura-presupuesto": { redirect: { to: "/categorias/gran-formato", statusCode: 301 } },
  "/product/planos-de-arquitectura-presupuesto/printestimate": { redirect: { to: "/categorias/gran-formato", statusCode: 301 } },
  "/product/plantilla-tarjeta-2": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/plantilla-tarjeta-9": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/poming-colgador-puerta-presupuesto/printestimate": { redirect: { to: "/productos/colgador-puerta-personalizado", statusCode: 301 } },
  "/product/posavasos-personalizados-presupuesto/printestimate": { redirect: { to: "/productos/posavasos", statusCode: 301 } },
  "/product/poster-personalizado-presupuesto/printestimate": { redirect: { to: "/productos/posters-personalizados", statusCode: 301 } },
  "/product/punto-de-libro-presupuesto/printestimate": { redirect: { to: "/productos/puntos-de-libro-personalizados", statusCode: 301 } },
  "/product/roll-up-presupuesto": { redirect: { to: "/productos/roll-up-personalizado", statusCode: 301 } },
  "/product/roll-up-presupuesto/printestimate": { redirect: { to: "/productos/roll-up-personalizado", statusCode: 301 } },
  "/product/sobrespara-cartas-presupuesto/printestimate": { redirect: { to: "/productos/sobres-personalizados", statusCode: 301 } },
  "/product/stoppers": { redirect: { to: "/productos/stoppers-lineal-personalizados", statusCode: 301 } },
  "/product/stoppers-presupuesto/printestimate": { redirect: { to: "/productos/stoppers-lineal-personalizados", statusCode: 301 } },
  "/product/stoppers/printestimate": { redirect: { to: "/productos/stoppers-lineal-personalizados", statusCode: 301 } },
  "/product/table-tent-presupuesto/printestimate": { redirect: { to: "/productos/tabletens-personalizados", statusCode: 301 } },
  "/product/tarjeta-con-esquinas-redondas": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-con-esquinas-redondas-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-con-esquinas-redondas/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-de-citas": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-de-citas-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-de-citas/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-de-visita-elegantes-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-material-reciclado": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-postal-correos": { redirect: { to: "/productos/tarjetas-postales-personalizadas", statusCode: 301 } },
  "/product/tarjeta-postal-correos-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-postales-personalizadas", statusCode: 301 } },
  "/product/tarjeta-postal-correos/printestimate": { redirect: { to: "/productos/tarjetas-postales-personalizadas", statusCode: 301 } },
  "/product/tarjeta-visita-barniz-selectivo-presupuesto": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-visita-profesional": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-visita-profesional-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjeta-visita-profesional/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjetas-de-invitacion": { redirect: { to: "/productos/invitaciones-y-tarjetones-personalizados", statusCode: 301 } },
  "/product/tarjetas-de-invitacion-presupuesto/printestimate": { redirect: { to: "/productos/invitaciones-y-tarjetones-personalizados", statusCode: 301 } },
  "/product/tarjetas-de-invitacion/printestimate": { redirect: { to: "/productos/invitaciones-y-tarjetones-personalizados", statusCode: 301 } },
  "/product/tarjetas-pvc-personalizadas": { redirect: { to: "/productos/tarjetas-pvc-personalizadas", statusCode: 301 } },
  "/product/tarjetas-pvc-personalizadas-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-pvc-personalizadas", statusCode: 301 } },
  "/product/tarjetas-pvc-personalizadas/printestimate": { redirect: { to: "/productos/tarjetas-pvc-personalizadas", statusCode: 301 } },
  "/product/tarjetas-rasca-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-rasca", statusCode: 301 } },
  "/product/tarjetas-visita-barniz-selectivo-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjetas-visitas-papel-reciclado": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjetas-visitas-papel-reciclado-presupuesto/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tarjetas-visitas-papel-reciclado/printestimate": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/product/tiras-impulso-presupuesto/printestimate": { redirect: { to: "/productos/tiras-de-lineal-personalizadas", statusCode: 301 } },
  "/product/totem-publicitario-presupuesto/printestimate": { redirect: { to: "/productos/totems-publicitarios-personalizados", statusCode: 301 } },
  "/product/triptico": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/product/triptico-presupuesto/printestimate": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/product/triptico/printestimate": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/product/vinilo-al-acido-presupuesto/printestimate": { redirect: { to: "/productos/vinilo-para-cristal", statusCode: 301 } },
  "/product/vinilo-alta-adherencia-presupuesto/printestimate": { redirect: { to: "/productos/vinilos-superficies-planas", statusCode: 301 } },
  "/product/vinilo-de-corte-presupuesto/printestimate": { redirect: { to: "/productos/vinilo-de-corte", statusCode: 301 } },
  "/product/vinilo-microperforado-presupuesto/printestimate": { redirect: { to: "/productos/vinilo-para-cristal", statusCode: 301 } },
  "/product/vinilo-para-coches-presupuesto/printestimate": { redirect: { to: "/productos/vinilo-vehiculos-personalizado", statusCode: 301 } },
  "/product/vinilo-para-cristales-presupuesto/printestimate": { redirect: { to: "/productos/vinilo-para-cristal", statusCode: 301 } },
  "/product/vinilo-removible-presupuesto/printestimate": { redirect: { to: "/productos/vinilos-superficies-planas", statusCode: 301 } },
  "/product/vinilo-suelo-presupuesto/printestimate": { redirect: { to: "/productos/vinilo-suelo-personalizado", statusCode: 301 } },
  "/product/vinilo-transparente-presupuesto/printestimate": { redirect: { to: "/productos/vinilo-para-cristal", statusCode: 301 } },
  "/producte/calendario-de-mesa-con-espiral": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/producte/lienzos": { redirect: { to: "/productos/carteles-personalizados-gran-formato", statusCode: 301 } },
  "/producte/samarretes": { redirect: { to: "/productos/dorsales-carrera", statusCode: 301 } },
  "/producto/agenda": { redirect: { to: "/productos/agendas-personalizadas", statusCode: 301 } },
  "/producto/backlights": { redirect: { to: "/productos/cajas-de-luz-personalizadas", statusCode: 301 } },
  "/producto/banderas": { redirect: { to: "/productos/banderolas-personalizadas", statusCode: 301 } },
  "/producto/banners": { redirect: { to: "/productos/xbanner-personalizado", statusCode: 301 } },
  "/producto/bloc-autocopiativo": { redirect: { to: "/productos/talonarios-autocopiativos-personalizados", statusCode: 301 } },
  "/producto/bloc-de-notas": { redirect: { to: "/productos/blocs-notas", statusCode: 301 } },
  "/producto/calendario-de-mesa-con-espiral": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/producto/calendario-de-pared-anual": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/producto/calendario-sobremesa": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/producto/calendarios": { redirect: { to: "/productos/calendarios-personalizados", statusCode: 301 } },
  "/producto/carpetas": { redirect: { to: "/productos/carpetas-de-presentacion-personalizadas", statusCode: 301 } },
  "/producto/carpetas-con-anillas": { redirect: { to: "/productos/archivadores-personalizados", statusCode: 301 } },
  "/producto/carta-de-restaurante": { redirect: { to: "/productos/cartas-restaurante-personalizadas", statusCode: 301 } },
  "/producto/catalogo-y-revistas-archivables": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/producto/catalogos-y-revistas-grapadas": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/producto/chanclas": { redirect: { to: "/categorias/eventos", statusCode: 301 } },
  "/producto/corporeos-y-3d": { redirect: { to: "/productos/letras-corporeas-personalizadas", statusCode: 301 } },
  "/producto/cupones": { redirect: { to: "/productos/cupones-promocionales", statusCode: 301 } },
  "/producto/delantal": { redirect: { to: "/categorias/hosteleria-restauracion", statusCode: 301 } },
  "/producto/diplomas": { redirect: { to: "/productos/diplomas-personalizados", statusCode: 301 } },
  "/producto/display-de-mesa-con-peana": { redirect: { to: "/productos/displays-de-mesa-personalizados", statusCode: 301 } },
  "/producto/doming-gota-de-resina": { redirect: { to: "/productos/etiquetas-doming", statusCode: 301 } },
  "/producto/dorsales-de-participacion": { redirect: { to: "/productos/dorsales-carrera", statusCode: 301 } },
  "/producto/estores": { redirect: { to: "/categorias/eventos", statusCode: 301 } },
  "/producto/etiquetas-adhesivas-de-papel": { redirect: { to: "/categorias/adhesivos-personalizados", statusCode: 301 } },
  "/producto/etiquetas-adhesivas-en-bobina": { redirect: { to: "/productos/etiquetas-adhesivas-en-bobina", statusCode: 301 } },
  "/producto/flyer": { redirect: { to: "/productos/flyers-personalizados", statusCode: 301 } },
  "/producto/folletos-plegados": { redirect: { to: "/productos/folletos-plegados-personalizados", statusCode: 301 } },
  "/producto/foto-en-carton-pluma": { redirect: { to: "/productos/panel-foam-personalizado", statusCode: 301 } },
  "/producto/foto-en-forex": { redirect: { to: "/productos/panel-forex", statusCode: 301 } },
  "/producto/identificadores-maleta": { redirect: { to: "/productos/identificador-maleta", statusCode: 301 } },
  "/producto/imanes": { redirect: { to: "/productos/imanes-publicitarios", statusCode: 301 } },
  "/producto/imanes-para-vehiculos": { redirect: { to: "/productos/lamina-magnetica-impresa", statusCode: 301 } },
  "/producto/impresion_banderolas": { redirect: { to: "/productos/banderolas-personalizadas", statusCode: 301 } },
  "/producto/laminado-velleda": { redirect: { to: "/productos/vinilo-suelo-personalizado", statusCode: 301 } },
  "/producto/lanyard": { redirect: { to: "/productos/lanyards-eventos-barcelona", statusCode: 301 } },
  "/producto/libretas": { redirect: { to: "/productos/libretas-personalizadas", statusCode: 301 } },
  "/producto/libros-bajo-demanda": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/producto/lienzos": { redirect: { to: "/productos/carteles-personalizados-gran-formato", statusCode: 301 } },
  "/producto/manteles-individuales": { redirect: { to: "/productos/manteles-individuales-personalizados", statusCode: 301 } },
  "/producto/memorias": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/producto/minutas": { redirect: { to: "/productos/minutas-boda", statusCode: 301 } },
  "/producto/mostradores": { redirect: { to: "/categorias/expositores", statusCode: 301 } },
  "/producto/paneles-de-pvc": { redirect: { to: "/categorias/gran-formato/material-rigido", statusCode: 301 } },
  "/producto/photocalls": { redirect: { to: "/productos/photocall-personalizado", statusCode: 301 } },
  "/producto/placas-de-metacrilato": { redirect: { to: "/productos/metacrilato-personalizado", statusCode: 301 } },
  "/producto/planos-arquitecto": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/producto/poming": { redirect: { to: "/productos/colgador-puerta-personalizado", statusCode: 301 } },
  "/producto/posavasos": { redirect: { to: "/productos/posavasos", statusCode: 301 } },
  "/producto/puntos-de-libro": { redirect: { to: "/productos/puntos-de-libro-personalizados", statusCode: 301 } },
  "/producto/roll-up": { redirect: { to: "/productos/roll-up-personalizado", statusCode: 301 } },
  "/producto/rotulacion-de-espacio": { redirect: { to: "/categorias/gran-formato", statusCode: 301 } },
  "/producto/sellos-de-goma": { redirect: { to: "/productos/sellos-de-goma-personalizados", statusCode: 301 } },
  "/producto/sobres-y-bolsas": { redirect: { to: "/productos/sobres-personalizados", statusCode: 301 } },
  "/producto/stoppers": { redirect: { to: "/productos/stoppers-lineal-personalizados", statusCode: 301 } },
  "/producto/tarjeta-comercial": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/producto/tarjeta-de-visita-con-barniz-selectivo": { redirect: { to: "/productos/tarjetas-de-visita-personalizadas", statusCode: 301 } },
  "/producto/tarjeta-felicitacion": { redirect: { to: "/productos/invitaciones-y-tarjetones-personalizados", statusCode: 301 } },
  "/producto/tarjeta-publicitaria": { redirect: { to: "/categorias/publicidad-oficina/material-publicitario", statusCode: 301 } },
  "/producto/tarjetas-especiales": { redirect: { to: "/categorias/publicidad-oficina/material-publicitario", statusCode: 301 } },
  "/producto/tesis-doctoral": { redirect: { to: "/categorias/libros-revistas-catalogos", statusCode: 301 } },
  "/producto/totem": { redirect: { to: "/productos/totems-publicitarios-personalizados", statusCode: 301 } },
  "/producto/vinilo-al-acido": { redirect: { to: "/productos/vinilo-para-cristal", statusCode: 301 } },
  "/producto/vinilos-adhesivos": { redirect: { to: "/categorias/adhesivos-personalizados", statusCode: 301 } },
  "/producto/vinilos-de-corte": { redirect: { to: "/productos/vinilo-de-corte", statusCode: 301 } },
  "/producto/vinilos-de-escaparate": { redirect: { to: "/productos/vinilo-para-cristal", statusCode: 301 } },
  "/productos/banderolas-lineal": { redirect: { to: "/productos/banderolas-lineal-personalizadas", statusCode: 301 } },
  "/productos/flyers-a5": { redirect: { to: "/productos/flyers-personalizados", statusCode: 301 } },
  "/productos/oficina": { redirect: { to: "/categorias/publicidad-oficina/material-oficina", statusCode: 301 } },
  "/shop": { redirect: { to: "/productos", statusCode: 301 } },
  "/sitemap": { redirect: { to: "/sitemap.xml", statusCode: 301 } },
  "/te-presentamos-kitbox-cajas-corporativas-personalizadas-para-trabajadores-y-clientes": { redirect: { to: "/categorias/packaging", statusCode: 301 } },
  "/categorias/adhesivos": {
    redirect: {
      to: "/categorias/adhesivos-personalizados",
      statusCode: 301,
    },
  },

  "/categorias/libros": {
    redirect: {
      to: "/categorias/libros-revistas-catalogos",
      statusCode: 301,
    },
  },
  "/category/expositores-publicitarios": {
  redirect: {
    to: "/categorias/expositores",
    statusCode: 301,
  },
},

"/category/folletos-publicitarios": {
  redirect: {
    to: "/productos/folletos-plegados-personalizados",
    statusCode: 301,
  },
},

"/category/imprimir-libros": {
  redirect: {
    to: "/categorias/libros-revistas-catalogos",
    statusCode: 301,
  },
},

"/category/imprimir-posters": {
  redirect: {
    to: "/productos/posters-personalizados",
    statusCode: 301,
  },
},

"/category/imprimir-tarjetas-de-visita": {
  redirect: {
    to: "/productos/tarjetas-de-visita-personalizadas",
    statusCode: 301,
  },
},

"/product/expositor-de-suelo-con-peana-presupuesto": {
  redirect: {
    to: "/categorias/expositores",
    statusCode: 301,
  },
},

"/product/folletos-troquelados-presupuesto": {
  redirect: {
    to: "/productos/flyers-con-forma-personalizados",
    statusCode: 301,
  },
},

"/product/impresion-en-metacrilato-presupuesto": {
  redirect: {
    to: "/productos/metacrilato-personalizado",
    statusCode: 301,
  },
},

"/product/dipticos-llave-habitacion-presupuesto": {
  redirect: {
    to: "/productos/tarjeta-habitacion-hotel",
    statusCode: 301,
  },
},

  "/category/articulos-promocionales": {
    redirect: {
      to: "/categorias/eventos",
      statusCode: 301,
    },
  },

  "/category/publicidad-en-puntos-de-venta": {
    redirect: {
      to: "/categorias/expositores",
      statusCode: 301,
    },
  },

  "/product/diptico-presupuesto": {
    redirect: {
      to: "/productos/folletos-plegados-personalizados",
      statusCode: 301,
    },
  },

} as const ;
