<!-- components/icons/social/InstagramIcon.vue -->
<template>
  <svg
    viewBox="0 0 24 24"
    aria-hidden="true"
    focusable="false"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="4"
      y="4"
      width="16"
      height="16"
      rx="5"
      stroke="currentColor"
      stroke-width="2"
    />
    <circle
      cx="12"
      cy="12"
      r="3.5"
      stroke="currentColor"
      stroke-width="2"
    />
    <circle
      cx="17"
      cy="7"
      r="1.2"
      fill="currentColor"
    />
  </svg>
</template>